#!/bin/sh
":"; //# comment; exec /usr/bin/env node --experimental-vm-modules "$0" "$@"
"use strict";
const program = require("commander");
const globby = require("globby");
const ts = require("typescript");
const fs = require("fs").promises;
const jscodeshift = require("jscodeshift");
const execSync = require("child_process").execSync;
const ParsedPlugin = require("./lib/ParsedPlugin").default;
const vm = require("vm"); // (useful for turning off when importing plugins in LipSurf.js

const FOLDER_REGX = /^src\/(.*)\/([^.]*).*$/;

program
  .option("-p, --project", "ts config file path", "./tsconfig.json")
  .option("-o, --out-dir <destination>", "destination", "dist");

program
  .command("build [...PLUGINS]")
  .description("build lipsurf plugins")
  .option("-w, --watch")
  .option("--no-base-imports")
  .action((plugins, cmdObj) => build({ ...cmdObj, ...cmdObj.parent }, plugins));

program
  .command("vup")
  .description("up the minor version of all the plugins")
  .option(
    "-v, --version <version>",
    "specify a version instead of incrementing the minor version by 1"
  )
  .action((cmdObj) => upVersion({ ...cmdObj, ...cmdObj.parent }));

const parseConfigHost /* : any */ = {
  fileExists: ts.sys.fileExists,
  readDirectory: ts.sys.readDirectory,
  readFile: ts.sys.readFile,
  useCaseSensitiveFileNames: true,
};
const configFileName = ts.findConfigFile(
  "./",
  ts.sys.fileExists,
  "tsconfig.json"
);

function compile(config) {
  let program = ts.createProgram(config.fileNames, config.options);
  let emitResult = program.emit();

  let allDiagnostics = ts
    .getPreEmitDiagnostics(program)
    .concat(emitResult.diagnostics);

  allDiagnostics.forEach((diagnostic) => {
    if (diagnostic.file) {
      let { line, character } = diagnostic.file.getLineAndCharacterOfPosition(
        diagnostic.start
      );
      let message = ts.flattenDiagnosticMessageText(
        diagnostic.messageText,
        "\n"
      );
      console.log(
        `${diagnostic.file.fileName} (${line + 1},${character + 1}): ${message}`
      );
    } else {
      console.log(
        `${ts.flattenDiagnosticMessageText(diagnostic.messageText, "\n")}`
      );
    }
  });

  if (emitResult.emitSkipped) throw "TypeScript compile errors.";
}

const formatHost = {
  getCanonicalFileName: (path) => path,
  getCurrentDirectory: ts.sys.getCurrentDirectory,
  getNewLine: () => ts.sys.newLine,
};

function watchTs() {
  // TypeScript can use several different program creation "strategies":
  //  * ts.createEmitAndSemanticDiagnosticsBuilderProgram,
  //  * ts.createSemanticDiagnosticsBuilderProgram
  //  * ts.createAbstractBuilder
  // The first two produce "builder programs". These use an incremental strategy
  // to only re-check and emit files whose contents may have changed, or whose
  // dependencies may have changes which may impact change the result of prior
  // type-check and emit.
  // The last uses an ordinary program which does a full type check after every
  // change.
  // Between `createEmitAndSemanticDiagnosticsBuilderProgram` and
  // `createSemanticDiagnosticsBuilderProgram`, the only difference is emit.
  // For pure type-checking scenarios, or when another tool/process handles emit,
  // using `createSemanticDiagnosticsBuilderProgram` may be more desirable.
  const createProgram = ts.createEmitAndSemanticDiagnosticsBuilderProgram;

  // Note that there is another overload for `createWatchCompilerHost` that takes
  // a set of root files.
  const host = ts.createWatchCompilerHost(
    configFileName,
    {},
    ts.sys,
    createProgram,
    reportDiagnostic,
    reportWatchStatusChanged
  );

  // You can technically override any given hook on the host, though you probably
  // don't need to.
  // Note that we're assuming `origCreateProgram` and `origPostProgramCreate`
  // doesn't use `this` at all.
  const origCreateProgram = host.createProgram;
  host.createProgram = (rootNames, options, host, oldProgram) => {
    console.log("Compiling changed typescript...");
    return origCreateProgram(rootNames, options, host, oldProgram);
  };
  const origPostProgramCreate = host.afterProgramCreate;

  host.afterProgramCreate = (program) => {
    console.log("Done compiling changed typescript.");
    origPostProgramCreate(program);
  };

  // `createWatchProgram` creates an initial program, watches files, and updates
  // the program over time.
  ts.createWatchProgram(host);
}

function reportDiagnostic(diagnostic) {
  console.error(
    "Error",
    diagnostic.code,
    ":",
    ts.flattenDiagnosticMessageText(
      diagnostic.messageText,
      formatHost.getNewLine()
    )
  );
}

/**
 * Prints a diagnostic every time the watch status changes.
 * This is mainly for messages like "Starting compilation" or "Compilation completed".
 */
function reportWatchStatusChanged(diagnostic) {
  console.info(ts.formatDiagnostic(diagnostic, formatHost));
}

class Linker {
  resolver;

  constructor(resolver, basedir) {
    this.resolver = resolver;
    this.basedir = basedir;
  }
  async link(specifier, referencingModule) {
    try {
      console.log(
        "baseDir",
        this.basedir,
        "specifier",
        specifier,
        "referencing module",
        referencingModule
      );
      // let filePath;
      // if (specifier.startsWith(".")) {
      //   filePath = `${specifier}.js`;
      // } else {
      //   filePath = `./node_modules/${specifier}`;
      // }
      const filePath = await new Promise((cb) =>
        this.resolver(
          specifier,
          {
            basedir: this.basedir,
          },
          (err, res) => cb(res)
        )
      );
      console.log("filepath", filePath);
      const file = await fs.readFile(filePath, "utf8");
      console.log("context", referencingModule.context);
      return new vm.SourceTextModule(file, {
        context: referencingModule.context,
      });
    } catch (e) {
      throw new Error(`Error linking ${specifier}`, e);
    }
    // Using `contextifiedObject` instead of `referencingModule.context`
    // here would work as well.
  }
}

async function build(options, plugins) {
  const EsBuild = require("esbuild");
  const resolve = require("resolve");

  if (typeof plugins === "undefined") plugins = [];
  let pluginNames = [].concat(plugins);
  const watch = options.watch;
  // import PluginBase and/or ExtensionUtil
  // if this is off, assume they already exist in global scope
  // where chrome-extension://.../plugin-base.js module obviously doesn't exist)
  const baseImports = options.baseImports;
  const timeStart = new Date();
  // const globbedTs = globby.sync(["src/*/*.ts", "!src/*/*.*.ts", "!src/@types"]);
  const globbedTs = globby.sync("dist/tmp/*/*.js");
  // const globbedTs = globby.sync(["src/*/*.ts", "!src/@types"]);
  if (!pluginNames.length) {
    pluginNames = Array.from(
      new Set(
        globbedTs
          .map((filePath) => FOLDER_REGX.exec(filePath))
          .filter((regxRes) => regxRes && regxRes[1] === regxRes[2])
          .map((regxRes) => regxRes[1])
      )
    );
  }
  // options.outDir, pluginNames, process.cwd() + "/", options.prod, baseImports;
  console.log("globbedTs", globbedTs);

  if (watch) {
  } else {
    // console.log("pluginNames", pluginNames);
    for (const pluginName of pluginNames) {
      const pluginWLanguageFiles = globbedTs
        .filter((x) => x.substr(x.lastIndexOf("/")).includes(pluginName))
        .sort((a, b) => a.length - b.length);
      const linker = new Linker(
        resolve,
        pluginWLanguageFiles[0].substr(
          0,
          pluginWLanguageFiles[0].lastIndexOf("/")
        )
      );
      // const codeParts = await Promise.all(
      //   pluginWLanguageFiles.map((f) => fs.readFile(f, { encoding: "utf8" }))
      // );
      console.log("globbed pluginNames", pluginWLanguageFiles);
      // make a temporary ts file that imports the other langs
      // (to avoid dupe names when just conjoining the plugins)
      // const transformed = EsBuild.buildSync({
      //   entryPoints: ,
      //   bundle: true,
      //   outdir: options.outDir,
      // });

      // console.log("transformed", transformed);
      // const codeParts = await Promise.all(
      //   pluginWLanguageFiles.map((f) => fs.readFile(f, { encoding: "utf8" }))
      // );
      const codeParts = [
        ...pluginWLanguageFiles.map((x, i) => {
          const name = x.substring(x.lastIndexOf("/") + 1, x.length - 3);
          return i === 0
            ? `import plugin from "./${name}";`
            : `import "./${name}";`;
        }),
        `export default plugin;`,
      ];

      const context = {
        // this: {},
        global: {},
        exports: {},
        module: {
          exports: {},
        },
        PluginBase: {
          languages: {},
        },
      };
      vm.createContext(context);
      const finalScript = codeParts.join("\n");
      console.log("codeParts", finalScript);
      const mod = new vm.SourceTextModule(finalScript, { context });
      try {
        await mod.link(linker.link.bind(linker));
      } catch (e) {
        console.error(`linking error`, e);
      }
      await mod.evaluate();
      console.log("mod", mod, "context", context, "namespace", mod.namespace);

      // EsBuild.build({
      //   entryPoints: ,
      //   bundle: true,
      //   outdir: options.outDir,
      // }).catch(() => process.exit(1));
    }
    const timeEnd = new Date();
    console.log(
      `Done building in ${Math.round((timeEnd - timeStart) / 1000)} seconds.`
    );
  }
}

async function upVersion(options) {
  // make sure there are no unexpected changes so that we don't include them in the upversion commit
  try {
    execSync(
      "git diff-index --ignore-submodules --quiet HEAD -- ./"
    ).toString();
  } catch (e) {
    throw new Error(
      `There are uncommitted things. Commit them before running vup.`
    );
  }
  // first find a plugin file
  const parDir = `${options.outDir}/tmp`;
  let files;
  try {
    files = fs.readdirSync(parDir);
  } catch (e) {
    console.warn(
      `Expected temporary build plugin files in ${parDir}. Running \`yarn build\` first. We need these to read the .mjs plugins (can't read ts directly for now) and extract a current version.`
    );
    execSync("yarn build");
    files = fs.readdirSync(parDir);
  }
  const allPluginNames = files.filter(
    (x) => !x.startsWith(".") || x.endsWith(".mjs"),
    {}
  );
  const anyPluginName = allPluginNames[0];
  const source = fs
    .readFileSync(`${parDir}/${anyPluginName}.joined.mjs`)
    .toString();
  const parsed = new ParsedPlugin(jscodeshift, source);
  const oldVersion = parsed.getVersion();

  console.log(`latest version of ${anyPluginName}: ${oldVersion}`);
  const versionSplit = oldVersion.split(".");
  const newVersion =
    options.version || `${versionSplit[0]}.${+versionSplit[1] + 1}.0`;
  console.log(`upping to: ${newVersion}`);
  execSync(
    `sed -i 's/version: "${oldVersion}"/version: "${newVersion}"/g' src/*/*.ts`
  );
  await build({ outDir: options.outDir, prod: true });
  // remove the old plugins
  try {
    execSync(`rm dist/*.${oldVersion.replace(/\./g, "-")}.*.ls`);
  } catch (e) {
    console.warn("error removing old version's files");
  }
  // make an vup commit (version tagging is done by the parent repo -- which determines which commit actually gets into the extension's package)
  execSync("git add src dist");
  // no longer doing this in the mono repo
  // execSync(`git commit -m "Version upped from ${oldVersion} to ${newVersion}" -a`);
}

program.parseAsync(process.argv).catch((e) => {
  console.error(e);
  process.exit(1);
});
